"""Konuşma içeriği: sesli cevap soruları + telaffuz kelimeleri."""

# Sesli cevap soruları. keywords: iyi bir cevapta geçmesi beklenen sözcükler (puanlama için, küçük harf).
PROMPTS = [
    {"id": "intro", "level": "A2", "q": "Introduce yourself. Tell us who you are, what you study, and what you like about programming.",
     "keywords": ["student", "software", "engineering", "university", "programming", "learn", "like"],
     "model": "Hello, my name is Elif. I'm a second-year software engineering student at Ankara University. I like programming because I can build useful things and solve problems. In my free time I learn mobile app development.",
     "tip": "Kısa tut: isim, bölüm, ilgi alanı. 3-4 cümle yeterli."},
    {"id": "api", "level": "B1", "q": "Explain what an API is, as if you were talking to a friend who is not a programmer.",
     "keywords": ["api", "program", "request", "data", "server", "rules", "talk"],
     "model": "An API is a set of rules that lets two programs talk to each other. For example, a weather app sends a request to a server, and the server sends back the data. The API defines how to ask and how the answer looks.",
     "tip": "Günlük bir benzetme kullan: garson, menü, mutfak gibi."},
    {"id": "stack-queue", "level": "B1", "q": "What is the difference between a stack and a queue?",
     "keywords": ["stack", "queue", "last", "first", "out", "item", "order"],
     "model": "A stack works as last in, first out. The last item you add is the first one you remove, like a pile of plates. A queue works as first in, first out, like people waiting in a line. The first item you add is the first one to leave.",
     "tip": "LIFO ve FIFO'yu İngilizce açıkla: last in first out / first in first out."},
    {"id": "git", "level": "B1", "q": "What is Git and why do developers use it?",
     "keywords": ["version", "control", "history", "changes", "branch", "team", "code", "track"],
     "model": "Git is a version control system. It tracks every change in the code, so we can see the history and go back to an older version if something breaks. It also lets many people work on the same project with branches and merge their work later.",
     "tip": "Üç fayda say: geçmiş, geri dönme, takım çalışması."},
    {"id": "project", "level": "B1", "q": "Describe a project that you built. What did it do and what was difficult?",
     "keywords": ["server", "built", "app", "data", "difficult", "learned"],
     "model": "I built a mobile app that shows the cafeteria menu of my university. It downloads the data from a server every day. The most difficult part was fixing the wrong dates in the school's files. I learned a lot about handling real data.",
     "tip": "Yapı: ne yaptım → nasıl çalışıyor → zor olan → öğrendiğim."},
    {"id": "standup", "level": "A2", "q": "Imagine you are in a daily stand-up. Tell your team what you did yesterday, what you will do today, and if you have any blockers.",
     "keywords": ["yesterday", "today", "will", "finished", "working", "blocker", "help"],
     "model": "Yesterday I finished the login screen. Today I will connect it to the server and write some tests. I don't have any blockers right now, but I may need help with the API later.",
     "tip": "Üç parça: yesterday / today / blockers."},
    {"id": "database", "level": "A2", "q": "What is a database and why do we need it?",
     "keywords": ["data", "store", "table", "information", "save", "query", "organized"],
     "model": "A database is an organized place to store data. Apps save information like users and orders in tables, and they can find it quickly with queries. Without a database, all the data would disappear when the program closes.",
     "tip": "Kullanıcılar ve siparişler gibi somut örnek ver."},
    {"id": "debug", "level": "B1", "q": "How do you debug a problem in your code? Describe your steps.",
     "keywords": ["error", "message", "reproduce", "test", "log", "breakpoint", "step", "fix"],
     "model": "First, I read the error message carefully. Then I try to reproduce the problem. I add logs or use a breakpoint to see the values of the variables. When I find the cause, I fix it and write a test so it does not come back.",
     "tip": "Sıra kullan: first, then, after that, finally."},
    {"id": "testing", "level": "B1", "q": "Why is testing important in software development?",
     "keywords": ["bugs", "test", "quality", "early", "confidence", "change", "automatic"],
     "model": "Testing helps us find bugs early, before the users see them. Automatic tests give us confidence when we change the code, because they tell us immediately if something stops working. In the end, good tests save time and money.",
     "tip": "Neden önemli? Erken hata bulma + güven + zaman kazancı."},
    {"id": "frontend-backend", "level": "A2", "q": "What is the difference between frontend and backend?",
     "keywords": ["frontend", "backend", "user", "server", "see", "data", "interface"],
     "model": "The frontend is the part that the user sees and uses, like buttons and pages. The backend runs on the server. It stores the data and does the logic, for example checking a password.",
     "tip": "Restoran benzetmesi: salon (frontend), mutfak (backend)."},
    {"id": "dream-job", "level": "B1", "q": "Describe your dream job in the tech industry.",
     "keywords": ["want", "work", "company", "team", "build", "products", "learn", "future"],
     "model": "My dream job is to work in a creative team that builds products for millions of people. I want to keep learning and to solve difficult problems. In the future, I would like to lead a team of engineers.",
     "tip": "I would like to / I want to kalıplarını kullan."},
    {"id": "recursion", "level": "B2", "q": "Explain recursion in simple words and give an example.",
     "keywords": ["function", "calls", "itself", "base", "case", "smaller", "problem", "example"],
     "model": "Recursion means that a function calls itself to solve a smaller version of the same problem. It must have a base case that stops the calls. For example, to calculate a factorial, the function multiplies the number by the factorial of the number minus one.",
     "tip": "Mutlaka 'base case' (durma koşulu) kavramını söyle."},
    {"id": "cloud", "level": "A2", "q": "What is the cloud? Explain it simply.",
     "keywords": ["internet", "servers", "computers", "storage", "pay", "use", "data"],
     "model": "The cloud means using computers and storage through the internet. Instead of buying your own servers, you rent them from a company and pay for what you use. It is easy to grow because you can add more resources when you need them.",
     "tip": "Kiralamak = rent, kullandığın kadar öde = pay for what you use."},
    {"id": "code-review-disagree", "level": "B2", "q": "A teammate disagrees with your solution in a code review. How do you handle it?",
     "keywords": ["listen", "understand", "discuss", "reason", "better", "respect", "agree", "compromise"],
     "model": "First, I listen carefully and try to understand their point of view. Then I explain my reasons politely. If their idea is better, I accept it. If we still disagree, we can ask a third person or find a compromise. The goal is better code, not winning.",
     "tip": "Nazik kalıplar: I see your point, but... / That's a good suggestion."},
    {"id": "strengths", "level": "B1", "q": "What are your strengths and weaknesses as a developer?",
     "keywords": ["strength", "weakness", "learn", "problem", "working", "time", "details"],
     "model": "My strength is that I learn quickly and I don't give up when I face a problem. My weakness is that I sometimes spend too much time on small details. I'm working on it by setting a time limit for each task.",
     "tip": "Zayıf yönü söylerken mutlaka 'I'm working on it' diye bitir."},
    {"id": "url", "level": "B2", "q": "What happens when you type a web address into your browser and press Enter?",
     "keywords": ["browser", "dns", "server", "request", "response", "html", "page", "ip"],
     "model": "First, the browser asks a DNS server for the IP address of the website. Then it sends a request to that server. The server sends back a response, usually HTML, and the browser renders it as a page on the screen.",
     "tip": "Adımları sırala: DNS → request → response → render."},
    {"id": "why-se", "level": "A2", "q": "Why did you choose software engineering?",
     "keywords": ["because", "like", "computers", "solve", "problems", "create", "interested", "future"],
     "model": "I chose software engineering because I'm interested in computers and I enjoy solving problems. I like creating things that people can use. Also, the field has many opportunities for the future.",
     "tip": "Because ile başla: Because I enjoy..."},
    {"id": "oop", "level": "B2", "q": "Explain object-oriented programming and its main ideas.",
     "keywords": ["objects", "class", "inheritance", "encapsulation", "polymorphism", "data", "methods"],
     "model": "Object-oriented programming organizes code into objects that combine data and methods. The main ideas are encapsulation, which hides the details, inheritance, which lets a class reuse another class, and polymorphism, which lets different objects respond to the same call in different ways.",
     "tip": "Dört kavram: abstraction, encapsulation, inheritance, polymorphism."},
]

# Telaffuz kelimeleri: (kelime, IPA (Amerikan), Türkçe ipucu)
WORDS = [
    ("cache", "/kæʃ/", "'keş' gibi; sonu 'ç' değil 'ş'. 'kaşe' DEĞİL."),
    ("queue", "/kjuː/", "Sadece 'kyu'. 'ueue' harfleri okunmaz."),
    ("schema", "/ˈskiːmə/", "'ski-ma'. 'sc' → 'sk'."),
    ("algorithm", "/ˈælɡərɪðəm/", "'ælgörıðım'; 'th' sesi dil dişin arasında."),
    ("asynchronous", "/eɪˈsɪŋkrənəs/", "'ey-SİNK-rı-nıs'; vurgu ikinci hecede."),
    ("deprecated", "/ˈdɛprəkeɪtɪd/", "'DEP-rı-key-tıd'; vurgu ilk hecede."),
    ("integer", "/ˈɪntɪdʒər/", "'İN-ti-cır'; g harfi 'c' gibi okunur."),
    ("recursion", "/rɪˈkɜːrʒən/", "'ri-KÖR-jın'; sondaki 'sion' → 'jın'."),
    ("parameter", "/pəˈræmɪtər/", "'pı-RÆ-mi-tır'; vurgu ikinci hecede."),
    ("iteration", "/ˌɪtəˈreɪʃən/", "'i-tı-REY-şın'."),
    ("boolean", "/ˈbuːliən/", "'BU-li-ın'."),
    ("authentication", "/ɔːˌθɛntɪˈkeɪʃən/", "'o-THEN-ti-KEY-şın'; 'th' sesi dil dişin arasında."),
    ("hierarchy", "/ˈhaɪərɑːrki/", "'HAY-ır-ar-ki'."),
    ("latency", "/ˈleɪtənsi/", "'LEY-tın-si'."),
    ("scalable", "/ˈskeɪləbəl/", "'SKEY-lı-bıl'."),
    ("sequence", "/ˈsiːkwəns/", "'Sİ-kwıns'."),
    ("binary", "/ˈbaɪnəri/", "'BAY-nı-ri'."),
    ("variable", "/ˈvɛəriəbəl/", "'VER-i-ı-bıl'."),
    ("Kubernetes", "/ˌkuːbərˈnɛtiːz/", "'ku-bır-NE-tis'."),
    ("middleware", "/ˈmɪdlwɛər/", "'MİD-ıl-wer'."),
    ("repository", "/rɪˈpɒzətɔːri/", "'ri-PAZ-ı-tor-i'."),
    ("regression", "/rɪˈɡrɛʃən/", "'ri-GREŞ-ın'."),
    ("vulnerability", "/ˌvʌlnərəˈbɪləti/", "'val-nır-ı-Bİ-lı-ti'."),
    ("encryption", "/ɪnˈkrɪpʃən/", "'in-KRİP-şın'."),
    ("abstraction", "/æbˈstrækʃən/", "'æb-STRÆK-şın'."),
    ("polymorphism", "/ˌpɒliˈmɔːrfɪzəm/", "'pa-li-MOR-fi-zım'."),
    ("encapsulation", "/ɪnˌkæpsjʊˈleɪʃən/", "'in-kæp-syu-LEY-şın'."),
    ("inheritance", "/ɪnˈhɛrɪtəns/", "'in-HE-ri-tıns'."),
    ("infrastructure", "/ˈɪnfrəˌstrʌktʃər/", "'İN-fri-strak-çır'."),
    ("specification", "/ˌspɛsɪfɪˈkeɪʃən/", "'spe-si-fi-KEY-şın'."),
    ("tolerance", "/ˈtɒlərəns/", "'TA-lı-rıns'."),
    ("resistance", "/rɪˈzɪstəns/", "'ri-ZİS-tıns'; 's' burada 'z' gibi."),
    ("voltage", "/ˈvoʊltɪdʒ/", "'VOL-tic'."),
    ("actuator", "/ˈæktʃueɪtər/", "'ÆK-çu-ey-tır'."),
    ("debug", "/diːˈbʌɡ/", "'di-BAG'."),
    ("developer", "/dɪˈvɛləpər/", "'di-VE-lı-pır'."),
    ("architecture", "/ˈɑːrkɪtɛktʃər/", "'AR-ki-tek-çır'."),
    ("synchronize", "/ˈsɪŋkrənaɪz/", "'SİNK-rı-nayz'."),
    ("exception", "/ɪkˈsɛpʃən/", "'ik-SEP-şın'."),
    ("deploy", "/dɪˈplɔɪ/", "'di-PLOY'."),
]


PROMPTS += [
    {"id": "flutter", "level": "B1", "q": "What is Flutter and why would a developer choose it?",
     "keywords": ["framework", "cross-platform", "widgets", "ios", "android", "code", "hot", "reload"],
     "model": "Flutter is a framework for building apps for iOS, Android, and the web with one code base. Everything on the screen is a widget, and hot reload shows changes instantly. Developers choose it because it saves time and works on many platforms.",
     "tip": "Üç neden söyle: tek kod, widget yapısı, hot reload."},
    {"id": "game-loop", "level": "B2", "q": "Explain what a game loop is and why it is important.",
     "keywords": ["loop", "update", "draw", "frame", "input", "player", "second"],
     "model": "A game loop is the main cycle of a game. In every frame it reads the input of the player, updates the objects, and draws the screen. This repeats many times per second, so the game feels smooth and alive.",
     "tip": "Üç adımı sırala: input → update → draw."},
    {"id": "ai-tools", "level": "B2", "q": "How do you use AI tools when you write code, and what are the risks?",
     "keywords": ["ai", "code", "check", "test", "risk", "understand", "wrong", "learn"],
     "model": "I use AI tools to get ideas and to explain errors, but I never copy the code without checking it. The tool can give a wrong answer, so I run the tests and read the documentation. My goal is to understand the code and to learn from it.",
     "tip": "Fayda + risk + kendi kontrolün: üç parça söyle."},
    {"id": "game-project", "level": "B1", "q": "Describe a game or app idea that you would like to build.",
     "keywords": ["game", "player", "build", "story", "fun", "plan"],
     "model": "I would like to build a runner game with a simple story. The player runs through different worlds, collects coins, and buys upgrades. I want the game to be fun and easy to learn, and I plan to add a leaderboard for friends.",
     "tip": "I would like to build... / The player... / I plan to... kalıplarını kullan."},
]
