"""Dinleme içeriği: diyaloglar + soruları. build_content.py bunu assets/data/listening.json'a çevirir.
Konuşmacı 0 ve 1 uygulamada farklı ses tonuyla okunur. Tek konuşmacılı metinlerde sadece 0 kullanılır."""

DIALOGUES = [
    {
        "id": "daily-standup", "title": "Daily Stand-up", "level": "A2", "minutes": 1,
        "about": "İki takım arkadaşı günlük toplantıda dünkü işlerini, bugünkü planlarını ve engellerini anlatıyor.",
        "lines": [
            (0, "Good morning, Tom. Let's start the stand-up."),
            (1, "Morning, Sara. Yesterday I finished the login page and fixed two small bugs."),
            (0, "Great. What are you working on today?"),
            (1, "Today I will connect the login page to the API. After that I will write some unit tests."),
            (0, "Do you have any blockers?"),
            (1, "Yes, one. I don't have the API key for the test server yet."),
            (0, "OK, I will ask the backend team right now. You should get it before lunch."),
            (1, "Thanks, that would help a lot. What about you?"),
            (0, "Yesterday I reviewed three pull requests. Today I will update the documentation and prepare the release notes."),
            (1, "Sounds good. Let's meet again tomorrow at nine."),
        ],
        "questions": [
            {"q": "What did Tom finish yesterday?", "options": ["The login page and two bug fixes", "The release notes", "Three pull requests", "The unit tests"], "answer": 0, "why": "Tom: 'I finished the login page and fixed two small bugs.'"},
            {"q": "What is Tom's blocker?", "options": ["A failing test", "He has no API key for the test server", "A merge conflict", "He is sick"], "answer": 1, "why": "API anahtarı henüz yok."},
            {"q": "What will Sara do today?", "options": ["Fix bugs", "Connect the login page", "Update the documentation and prepare release notes", "Talk to the client"], "answer": 2, "why": "Sara dokümantasyonu güncelleyip release notes hazırlayacak."},
        ],
    },
    {
        "id": "code-review", "title": "A Code Review", "level": "B1", "minutes": 1,
        "about": "Bir geliştirici, takım arkadaşının pull request'ini inceliyor ve önerilerde bulunuyor.",
        "lines": [
            (0, "Hi Ali, I looked at your pull request. Overall it looks good, but I have a few comments."),
            (1, "Thanks for the quick review. What did you find?"),
            (0, "First, the function that calculates the discount is too long. It does three different things."),
            (1, "You're right. Should I split it into smaller functions?"),
            (0, "Yes, that would make it easier to read and to test. Also, the variable name 'x' is not very clear."),
            (1, "Good point. I will rename it to 'totalPrice'."),
            (0, "One more thing. I could not find a test for the case when the cart is empty."),
            (1, "Oh, I forgot that edge case. I'll add a unit test for it today."),
            (0, "Perfect. Once you push the changes, I will approve the pull request."),
            (1, "Great, thanks for the helpful feedback."),
        ],
        "questions": [
            {"q": "What is the problem with the discount function?", "options": ["It has a syntax error", "It is too slow", "It is too long and does several things", "It has no name"], "answer": 2, "why": "'It is too long. It does three different things.'"},
            {"q": "Why does the reviewer mention the variable 'x'?", "options": ["The name is not clear", "It is never used", "It is a constant", "It causes a bug"], "answer": 0, "why": "'x' isim olarak anlaşılır değil."},
            {"q": "What test is missing?", "options": ["A test for a large cart", "A test for an empty cart", "A performance test", "A security test"], "answer": 1, "why": "Boş sepet (empty cart) için test yok."},
            {"q": "When will the reviewer approve the pull request?", "options": ["Right now", "After Ali pushes the changes", "Next week", "Never"], "answer": 1, "why": "'Once you push the changes, I will approve...'"},
        ],
    },
    {
        "id": "bug-report", "title": "Reporting a Bug", "level": "B1", "minutes": 1,
        "about": "Bir test uzmanı ve bir geliştirici, uygulamanın çökmesine neden olan hatayı birlikte yeniden üretmeye çalışıyor.",
        "lines": [
            (0, "Hi Daniel, I found a serious bug in the mobile app. It crashes when I upload a profile photo."),
            (1, "Can you reproduce it every time?"),
            (0, "Almost every time. It only happens when the photo is larger than five megabytes."),
            (1, "Interesting. Which phone and which version of the app are you using?"),
            (0, "An iPhone 13, version 2.4.1. I attached the crash log to the ticket."),
            (1, "Thanks. I think the problem is the file size limit. The server might reject large files without sending an error message."),
            (0, "That makes sense. The app just freezes and then closes."),
            (1, "I will add a check before the upload and show a friendly message to the user."),
            (0, "Good idea. Can you also give me a workaround for the testers?"),
            (1, "Sure. For now, they can use smaller photos. I will fix it in the next patch."),
        ],
        "questions": [
            {"q": "When does the app crash?", "options": ["When logging in", "When uploading a photo larger than 5 MB", "When the phone is offline", "When the app updates"], "answer": 1, "why": "Fotoğraf 5 MB'den büyükse çöküyor."},
            {"q": "What did the tester attach to the ticket?", "options": ["A screenshot", "A video", "The crash log", "The source code"], "answer": 2, "why": "'I attached the crash log to the ticket.'"},
            {"q": "What is the workaround for the testers?", "options": ["Use a different phone", "Use smaller photos", "Restart the server", "Wait for a month"], "answer": 1, "why": "Geçici çözüm: daha küçük fotoğraf kullanmak."},
        ],
    },
    {
        "id": "job-interview", "title": "A Junior Developer Interview", "level": "B1", "minutes": 2,
        "about": "Bir şirket, stajyer/junior geliştirici adayıyla projeleri ve güçlü yönleri hakkında konuşuyor.",
        "lines": [
            (0, "Welcome, Elif. Thank you for coming. Could you tell me a little about yourself?"),
            (1, "Thank you for having me. I'm a second-year software engineering student. I enjoy building mobile apps and solving problems."),
            (0, "Can you describe a project you are proud of?"),
            (1, "Yes. Last semester I built a mobile app that shows cafeteria menus for universities. It reads the data from a server and updates every day."),
            (0, "That sounds useful. What was the hardest part?"),
            (1, "The data from the school was sometimes wrong, so I wrote code to detect and fix mistakes automatically."),
            (0, "How do you work in a team?"),
            (1, "I try to communicate clearly. If I'm blocked, I ask for help early. I also like code reviews because I learn a lot from them."),
            (0, "What is one weakness you are working on?"),
            (1, "I sometimes spend too much time making code perfect. Now I try to finish a working version first and improve it later."),
            (0, "Thank you, Elif. We will contact you next week."),
        ],
        "questions": [
            {"q": "What kind of project did Elif describe?", "options": ["A video game", "A mobile app for cafeteria menus", "A banking system", "A website for a shop"], "answer": 1, "why": "Üniversite yemekhane menüsü uygulaması."},
            {"q": "What was the hardest part of her project?", "options": ["Designing the logo", "Finding users", "Fixing wrong data from the school", "Paying for servers"], "answer": 2, "why": "Okuldan gelen veri bazen yanlıştı."},
            {"q": "What does Elif do when she is blocked?", "options": ["Waits silently", "Asks for help early", "Changes the project", "Stops working"], "answer": 1, "why": "'If I'm blocked, I ask for help early.'"},
            {"q": "What is her weakness?", "options": ["She is always late", "She spends too much time making code perfect", "She does not like teams", "She cannot test code"], "answer": 1, "why": "Kodu mükemmel yapmaya fazla zaman harcıyor."},
        ],
    },
    {
        "id": "git-help", "title": "Help with Git", "level": "A2", "minutes": 1,
        "about": "Bir stajyer, kıdemli bir arkadaşından dal (branch) ve birleştirme çakışması konusunda yardım istiyor.",
        "lines": [
            (0, "Excuse me, Mark. Do you have a minute? I have a problem with Git."),
            (1, "Sure, Nina. What's wrong?"),
            (0, "I tried to merge my branch into main, but I got a conflict."),
            (1, "Don't worry, conflicts are normal. It means two people changed the same line."),
            (0, "What should I do now?"),
            (1, "Open the file. You will see markers that show both versions. Choose the correct code and delete the markers."),
            (0, "And then?"),
            (1, "Save the file, add it, and create a new commit. Then push your branch."),
            (0, "That sounds easy. Thank you so much!"),
            (1, "No problem. Next time, pull the latest changes before you start working. It helps to avoid conflicts."),
        ],
        "questions": [
            {"q": "What problem does Nina have?", "options": ["She cannot install Git", "She has a merge conflict", "She lost her password", "She deleted a branch"], "answer": 1, "why": "Merge conflict (birleştirme çakışması) yaşıyor."},
            {"q": "What does a conflict mean?", "options": ["The server is down", "Two people changed the same line", "The branch is old", "Git is broken"], "answer": 1, "why": "Aynı satırı iki kişi değiştirmiş."},
            {"q": "How can she avoid conflicts next time?", "options": ["Work on the main branch only", "Pull the latest changes before she starts", "Use a different computer", "Write shorter code"], "answer": 1, "why": "Çalışmaya başlamadan önce son değişiklikleri çekmek."},
        ],
    },
    {
        "id": "production-incident", "title": "A Production Incident", "level": "B2", "minutes": 2,
        "about": "Canlı ortamda bir kesinti yaşanıyor; ekip sorunu bulup önceki sürüme dönüyor ve sonraki adımları konuşuyor.",
        "lines": [
            (0, "Everyone, we have an incident. The website is returning errors for about thirty percent of the users."),
            (1, "I'm looking at the monitoring dashboard now. The error rate went up right after the last release."),
            (0, "How long ago did we deploy?"),
            (1, "About twenty minutes ago. The new version changed how we connect to the database."),
            (0, "Then the safest option is to roll back to the previous version. Do we agree?"),
            (1, "Yes. I'll start the rollback right now. It should take around five minutes."),
            (0, "While you do that, I will update the status page and inform the customers."),
            (1, "The rollback is complete. Error rates are dropping. Everything looks normal again."),
            (0, "Great work. Let's write down a timeline of what happened while it is still fresh."),
            (1, "Agreed. Tomorrow we should hold a postmortem and find out why our tests did not catch this problem."),
            (0, "Yes, and we should add an alert for database connection errors so we notice it faster next time."),
        ],
        "questions": [
            {"q": "How many users were affected?", "options": ["About ten percent", "About thirty percent", "All of them", "Nobody"], "answer": 1, "why": "'about thirty percent of the users'."},
            {"q": "What caused the problem?", "options": ["A hardware failure", "A change in how the app connects to the database", "A network attack", "A power cut"], "answer": 1, "why": "Yeni sürüm veritabanı bağlantısını değiştirmişti."},
            {"q": "What was the decision?", "options": ["Fix the code live", "Shut down the website", "Roll back to the previous version", "Ignore the errors"], "answer": 2, "why": "Önceki sürüme geri dönmek (roll back)."},
            {"q": "What will they do tomorrow?", "options": ["Release a new version", "Hold a postmortem", "Hire new people", "Change the database"], "answer": 1, "why": "Postmortem toplantısı yapacaklar."},
        ],
    },
    {
        "id": "sprint-planning", "title": "Sprint Planning", "level": "B1", "minutes": 1,
        "about": "Scrum takımı iki haftalık sprint için iş listesinden görev seçiyor ve tahmin yapıyor.",
        "lines": [
            (0, "Let's start the sprint planning. Our goal for this sprint is to release the new search feature."),
            (1, "I looked at the backlog. The search story has the highest priority."),
            (0, "How long do you think it will take?"),
            (1, "I estimate about five days for the backend and three days for the frontend."),
            (0, "That is a lot. Can we reduce the scope?"),
            (1, "We could skip the filters for now and add them in the next sprint."),
            (0, "Good idea. Let's focus on a simple version first. What about the bug fixes?"),
            (1, "We have two critical bugs. I suggest we fix them first because they affect many users."),
            (0, "Agreed. Then we will have enough time for the search feature and some testing."),
            (1, "Perfect. I will create the tasks and assign them to the team."),
        ],
        "questions": [
            {"q": "What is the goal of the sprint?", "options": ["Fix all bugs", "Release the new search feature", "Hire a designer", "Update the database"], "answer": 1, "why": "Hedef yeni arama özelliği."},
            {"q": "How do they reduce the scope?", "options": ["Skip testing", "Skip the filters for now", "Remove the backend", "Work on weekends"], "answer": 1, "why": "Filtreleri sonraki sprint'e bırakıyorlar."},
            {"q": "Why do they fix the critical bugs first?", "options": ["They are easy", "They affect many users", "The manager asked", "They are interesting"], "answer": 1, "why": "Çok sayıda kullanıcıyı etkiliyorlar."},
        ],
    },
    {
        "id": "requirements-chat", "title": "Clarifying Requirements", "level": "B2", "minutes": 2,
        "about": "Bir analist müşteriden \"hızlı bir uygulama\" isteğinin ne anlama geldiğini netleştirmesini istiyor.",
        "lines": [
            (0, "Thanks for meeting with us. You mentioned that you want the app to be fast. Could you clarify what that means for you?"),
            (1, "Well, our users get frustrated when they wait. I want pages to open immediately."),
            (0, "Let's be more specific. Would two seconds be acceptable for the main page?"),
            (1, "Two seconds is fine, but the search results must appear in less than one second."),
            (0, "Understood. How many users do you expect at the same time?"),
            (1, "Right now about five hundred, but we plan to grow to ten thousand within a year."),
            (0, "In that case, we should design the system to be scalable from the beginning."),
            (1, "Will that make the project more expensive?"),
            (0, "Slightly, but it will save money later. Otherwise you would need to rebuild the system when you grow."),
            (1, "That makes sense. Please write these points in the specification so we can approve them."),
            (0, "Of course. I'll send you a draft by Friday."),
        ],
        "questions": [
            {"q": "What must happen in less than one second?", "options": ["The main page loading", "Search results appearing", "Logging in", "Sending emails"], "answer": 1, "why": "Arama sonuçları 1 saniyeden kısa sürede gelmeli."},
            {"q": "How many users does the client expect in a year?", "options": ["Five hundred", "Five thousand", "Ten thousand", "One million"], "answer": 2, "why": "Bir yıl içinde on bin kullanıcı."},
            {"q": "Why does the analyst recommend a scalable design?", "options": ["It looks nicer", "It saves money later", "It is required by law", "It is simpler"], "answer": 1, "why": "Sonradan sistemi yeniden yazmak zorunda kalmamak için."},
            {"q": "When will the analyst send the draft?", "options": ["Tomorrow", "By Friday", "Next month", "Today"], "answer": 1, "why": "'I'll send you a draft by Friday.'"},
        ],
    },
    {
        "id": "pair-programming", "title": "Pair Programming", "level": "B1", "minutes": 1,
        "about": "İki geliştirici birlikte çalışarak bir döngüdeki hatayı buluyor.",
        "lines": [
            (0, "OK, I'm the driver, so I will type. You are the navigator, so you tell me what to think about."),
            (1, "Sounds good. The goal is to find out why the list is empty at the end."),
            (0, "Let me add a breakpoint inside the loop and run the debugger."),
            (1, "Look at the variable 'count'. It is always zero."),
            (0, "You're right. Wait... I see it. We create a new list on every iteration."),
            (1, "Exactly. We should create the list before the loop and only add items inside it."),
            (0, "Let me fix that. Now I run the code again."),
            (1, "It works! The list has twelve items. Let's write a test so this bug cannot come back."),
            (0, "Good idea. Pair programming is really helpful. I would not have seen that alone."),
        ],
        "questions": [
            {"q": "What is the bug?", "options": ["The loop never starts", "A new list is created on every iteration", "The variable has the wrong name", "The test is missing"], "answer": 1, "why": "Her turda yeni liste oluşturuluyor."},
            {"q": "What does the navigator do?", "options": ["Types the code", "Tells the driver what to think about", "Runs the server", "Writes documentation"], "answer": 1, "why": "Navigator yönlendirir, driver yazar."},
            {"q": "What do they do after the fix?", "options": ["Go home", "Write a test", "Delete the list", "Restart the computer"], "answer": 1, "why": "Hatanın geri gelmemesi için test yazıyorlar."},
        ],
    },
    {
        "id": "onboarding-day", "title": "First Day at the Company", "level": "A2", "minutes": 1,
        "about": "Yeni bir çalışan ilk gün iş arkadaşıyla geliştirme ortamını kuruyor.",
        "lines": [
            (0, "Welcome to the team, Can! I'm Julia. I will help you during your first week."),
            (1, "Thank you, Julia. I'm a little nervous, but I'm excited."),
            (0, "Don't worry. First, let's set up your laptop. You need to install the editor and clone the main repository."),
            (1, "Which version control system do you use?"),
            (0, "We use Git. I will give you access to our repository on GitHub."),
            (1, "Great. Where can I find the documentation?"),
            (0, "It is in the wiki. Please read the getting started page today."),
            (1, "OK. And when is the team meeting?"),
            (0, "Every morning at nine thirty. It's a short stand-up. You can just say what you plan to learn today."),
            (1, "That sounds friendly. Thank you for your help."),
        ],
        "questions": [
            {"q": "What must Can install first?", "options": ["A game", "The editor and the repository", "A new phone", "A virus scanner"], "answer": 1, "why": "Editör kurup ana depoyu klonlayacak."},
            {"q": "Where is the documentation?", "options": ["In an email", "In the wiki", "On paper", "In the kitchen"], "answer": 1, "why": "Dokümantasyon wiki'de."},
            {"q": "When is the daily team meeting?", "options": ["At nine thirty every morning", "At five every evening", "Once a month", "On Fridays only"], "answer": 0, "why": "Her sabah 09:30."},
        ],
    },
    {
        "id": "tech-talk-microservices", "title": "Short Talk: Why We Moved to Microservices", "level": "B2", "minutes": 2,
        "about": "Tek konuşmacılı kısa bir teknik sunum: bir şirket monolit yapıdan mikroservislere neden geçti?",
        "lines": [
            (0, "Good afternoon, everyone. Today I want to talk about why our company moved from a monolith to microservices."),
            (0, "Three years ago, our application was one big program. Every team worked in the same code base. It was simple at the beginning, but it became harder every month."),
            (0, "First, a small change required us to deploy the whole application. A tiny bug in one module could bring down everything."),
            (0, "Second, the teams were blocking each other. They had to wait for each other before they could release anything."),
            (0, "So we split the system into small services. Each service has one job, its own database, and its own team."),
            (0, "The result was positive. We now deploy many times a day, and a failure in one service does not stop the others."),
            (0, "However, microservices are not free. We needed better monitoring, and the network between services became a new source of problems."),
            (0, "My advice is simple. Do not start with microservices. Start simple, and split the system only when the pain is real. Thank you for listening."),
        ],
        "questions": [
            {"q": "What was the old application like?", "options": ["Many small services", "One big program", "A mobile app", "A spreadsheet"], "answer": 1, "why": "Tek büyük program (monolith)."},
            {"q": "What is one advantage of microservices mentioned?", "options": ["They are cheaper", "A failure in one service does not stop the others", "They need no monitoring", "They remove the network"], "answer": 1, "why": "Bir servisteki hata diğerlerini durdurmuyor."},
            {"q": "What is the speaker's advice?", "options": ["Always start with microservices", "Never use microservices", "Start simple and split only when needed", "Hire more people"], "answer": 2, "why": "Basit başla, sadece gerçekten gerektiğinde böl."},
            {"q": "What new problem did microservices create?", "options": ["Slow typing", "The network between services", "Too few teams", "No databases"], "answer": 1, "why": "Servisler arası ağ yeni sorun kaynağı oldu."},
        ],
    },
    {
        "id": "release-debate", "title": "Release on Friday?", "level": "B1", "minutes": 1,
        "about": "İki mühendis, yeni sürümü cuma günü yayınlamanın riskli olup olmadığını tartışıyor.",
        "lines": [
            (0, "The new version is ready. I think we should deploy it today."),
            (1, "Today is Friday. I'm not sure that's a good idea."),
            (0, "Why not? All the tests are green."),
            (1, "If something goes wrong, we will have to work during the weekend. And half of the team is already gone."),
            (0, "That's a fair point. But the customers are waiting for this feature."),
            (1, "What if we release on Monday morning instead? Then everyone is here and we can react quickly."),
            (0, "OK, I see your point. A delay of one weekend is not a big risk."),
            (1, "Great. In the meantime, we can test it once more in the staging environment."),
            (0, "Agreed. I'll tell the product manager that we will deploy on Monday."),
        ],
        "questions": [
            {"q": "Why is the second speaker against releasing on Friday?", "options": ["The tests are red", "They may have to work during the weekend", "The feature is not ready", "The server is old"], "answer": 1, "why": "Sorun çıkarsa hafta sonu çalışmak gerekir."},
            {"q": "When do they decide to release?", "options": ["Today", "Monday morning", "Next month", "Tomorrow night"], "answer": 1, "why": "Pazartesi sabahı."},
            {"q": "What will they do in the meantime?", "options": ["Nothing", "Test again in staging", "Delete the feature", "Change the team"], "answer": 1, "why": "Staging ortamında bir kez daha test."},
        ],
    },
]

# Dikte + sesli okuma için cümleler: (cümle, seviye, Türkçesi)
SENTENCES = [
    ("The function returns true if the file exists.", "A2", "Dosya varsa fonksiyon true döndürür."),
    ("I fixed the bug and pushed my changes.", "A2", "Hatayı düzelttim ve değişikliklerimi gönderdim."),
    ("Please send me the link to the repository.", "A2", "Lütfen bana deponun bağlantısını gönder."),
    ("Our daily stand-up starts at nine o'clock.", "A2", "Günlük toplantımız dokuzda başlıyor."),
    ("The server is down, so the app does not work.", "A2", "Sunucu kapalı, bu yüzden uygulama çalışmıyor."),
    ("I'm learning how to write clean code.", "A2", "Temiz kod yazmayı öğreniyorum."),
    ("Can you review my pull request today?", "A2", "Bugün pull request'imi inceleyebilir misin?"),
    ("The database stores all customer information.", "A2", "Veritabanı tüm müşteri bilgilerini saklar."),
    ("We need to test the new feature before the release.", "B1", "Yayından önce yeni özelliği test etmemiz gerekiyor."),
    ("The application crashes when the user uploads a large file.", "B1", "Kullanıcı büyük bir dosya yüklediğinde uygulama çöküyor."),
    ("I couldn't reproduce the error on my computer.", "B1", "Hatayı kendi bilgisayarımda yeniden üretemedim."),
    ("Could you explain how this algorithm works?", "B1", "Bu algoritmanın nasıl çalıştığını açıklar mısın?"),
    ("We deploy to production every Thursday afternoon.", "B1", "Her perşembe öğleden sonra canlıya çıkıyoruz."),
    ("The API returns the data in JSON format.", "B1", "API veriyi JSON biçiminde döndürür."),
    ("Writing tests helps us find problems early.", "B1", "Test yazmak sorunları erken bulmamıza yardım eder."),
    ("She works as a backend developer in a small startup.", "B1", "Küçük bir girişimde arka uç geliştirici olarak çalışıyor."),
    ("Every module should have a single responsibility.", "B1", "Her modülün tek bir sorumluluğu olmalı."),
    ("I'd like to apply for the summer internship at your company.", "B1", "Şirketinizdeki yaz stajına başvurmak istiyorum."),
    ("The error message was not clear, so I asked my teammate for help.", "B1", "Hata mesajı net değildi, bu yüzden takım arkadaşımdan yardım istedim."),
    ("We use version control to track every change in the code.", "B1", "Koddaki her değişikliği izlemek için sürüm kontrolü kullanıyoruz."),
    ("The new release fixes several security vulnerabilities.", "B2", "Yeni sürüm birkaç güvenlik açığını kapatıyor."),
    ("Asynchronous calls prevent the interface from freezing.", "B2", "Eşzamansız çağrılar arayüzün donmasını önler."),
    ("Good documentation is as important as good code.", "B2", "İyi dokümantasyon, iyi kod kadar önemlidir."),
    ("We need a scalable architecture that can handle a million users.", "B2", "Bir milyon kullanıcıyı kaldırabilecek ölçeklenebilir bir mimariye ihtiyacımız var."),
    ("The team decided to refactor the legacy code instead of rewriting it.", "B2", "Ekip eski kodu baştan yazmak yerine yeniden düzenlemeye karar verdi."),
    ("Technical debt grows when we skip tests to meet a deadline.", "B2", "Son teslim tarihine yetişmek için testleri atladığımızda teknik borç büyür."),
    ("The latency increased because the cache was not working properly.", "B2", "Önbellek düzgün çalışmadığı için gecikme arttı."),
    ("Before we merge, please resolve the conflicts and run all the tests.", "B2", "Birleştirmeden önce lütfen çakışmaları çöz ve tüm testleri çalıştır."),
    ("The project is on track, but we are slightly behind schedule on the mobile app.", "B2", "Proje planlandığı gibi gidiyor ama mobil uygulamada programın biraz gerisindeyiz."),
    ("An engineer must balance cost, safety, and performance in every design.", "B2", "Bir mühendis her tasarımda maliyet, güvenlik ve performansı dengelemelidir."),
    ("The sensor sends a signal to the controller every ten milliseconds.", "B1", "Sensör her on milisaniyede bir kontrolcüye sinyal gönderir."),
    ("Passwords should be stored as hashes, never as plain text.", "B2", "Parolalar asla düz metin olarak değil, özet (hash) olarak saklanmalıdır."),
    ("Could you elaborate on the requirements for the login screen?", "B2", "Giriş ekranının gereksinimlerini biraz açabilir misin?"),
    ("I will follow up with the client and send you an update tomorrow.", "B1", "Müşteriyle iletişime geçip yarın sana bir güncelleme göndereceğim."),
    ("Our application supports both Android and iOS.", "A2", "Uygulamamız hem Android'i hem iOS'u destekliyor."),
    ("The user interface should be simple and easy to use.", "A2", "Kullanıcı arayüzü basit ve kullanımı kolay olmalı."),
    ("I'm responsible for the frontend of this project.", "A2", "Bu projenin ön yüzünden ben sorumluyum."),
    ("Let me share my screen so you can see the problem.", "A2", "Sorunu görebilmen için ekranımı paylaşayım."),
    ("The deadline is next Friday, so we have to hurry.", "A2", "Son teslim tarihi gelecek cuma, bu yüzden acele etmeliyiz."),
    ("A good engineer never stops learning new technologies.", "B1", "İyi bir mühendis yeni teknolojiler öğrenmeyi asla bırakmaz."),
    ("When did you start learning to program?", "A2", "Programlamayı öğrenmeye ne zaman başladın?"),
    ("The pipeline failed because one of the tests did not pass.", "B1", "Testlerden biri geçmediği için iş hattı başarısız oldu."),
    ("We rolled back the update because it caused a serious problem.", "B1", "Ciddi bir soruna yol açtığı için güncellemeyi geri aldık."),
    ("Dependency injection makes the code easier to test and maintain.", "B2", "Bağımlılık enjeksiyonu kodu test etmeyi ve sürdürmeyi kolaylaştırır."),
    ("The algorithm has a time complexity of order n log n.", "B2", "Algoritmanın zaman karmaşıklığı n log n mertebesindedir."),
    ("I prefer to write the tests first and then implement the feature.", "B1", "Önce testleri yazıp sonra özelliği uygulamayı tercih ederim."),
    ("Our mentor gave us valuable feedback on our final presentation.", "B1", "Mentorumuz final sunumumuz hakkında değerli geri bildirim verdi."),
    ("It is important to validate user input to prevent attacks.", "B2", "Saldırıları önlemek için kullanıcı girdisini doğrulamak önemlidir."),
    ("The project failed because the requirements kept changing.", "B2", "Gereksinimler sürekli değiştiği için proje başarısız oldu."),
    ("Do you have any questions about the task?", "A2", "Görevle ilgili sorun var mı?"),
]


DIALOGUES += [
    {
        "id": "flutter-team-chat", "title": "Building a Flutter App", "level": "B1", "minutes": 1,
        "about": "İki geliştirici Flutter uygulamasının ekranını hot reload ile tasarlıyor ve yayına hazırlanıyor.",
        "lines": [
            (0, "How is the new screen coming along?"),
            (1, "Pretty well. I built the layout with a few widgets, and hot reload makes the work really fast."),
            (0, "Nice. Did you test it on a real phone or only on the emulator?"),
            (1, "Only on the emulator so far. Tomorrow I will install it on my phone and check the animation."),
            (0, "Good. Remember that the app has to work offline too."),
            (1, "Yes, I save the last data in local storage, so the menu still appears without internet."),
            (0, "Perfect. When do you want to send it to the App Store?"),
            (1, "After I fix the crash report from yesterday. I will also increase the build number."),
            (0, "OK. Let me know when it is ready, and I will review the code."),
        ],
        "questions": [
            {"q": "Why does the developer like hot reload?", "options": ["It makes the app smaller", "It makes the work very fast", "It fixes crashes", "It works offline"], "answer": 1, "why": "Hot reload çalışmayı çok hızlandırıyor."},
            {"q": "Where has the screen been tested so far?", "options": ["On a real phone", "Only on the emulator", "On a tablet", "On the web only"], "answer": 1, "why": "Şimdilik sadece emülatörde."},
            {"q": "How does the app work without internet?", "options": ["It saves the last data in local storage", "It downloads a video", "It cannot work offline", "It uses a printed menu"], "answer": 0, "why": "Son veriyi yerel depolamada saklıyor."},
            {"q": "What must be done before sending the app to the App Store?", "options": ["Delete the layout", "Fix the crash and increase the build number", "Buy a new phone", "Change the language"], "answer": 1, "why": "Çökmeyi düzeltmek ve derleme numarasını artırmak."},
        ],
    },
    {
        "id": "game-design-review", "title": "A Game Design Review", "level": "B1", "minutes": 1,
        "about": "Bir oyun tasarımcısı ve bir programcı, koşu oyununun zorluk eğrisini ve oyun testinden gelen geri bildirimi konuşuyor.",
        "lines": [
            (0, "I watched three friends playtest the runner game yesterday. Most of them lost in the first minute."),
            (1, "That means the difficulty curve is too steep. The first obstacles come too fast."),
            (0, "Exactly. I suggest we spawn fewer enemies at the beginning and add them slowly."),
            (1, "I can do that. I will also make the collider of the spikes a little smaller, because the players say it feels unfair."),
            (0, "Good idea. What about the power-ups?"),
            (1, "The magnet power-up is popular. People love it when the coins fly to the character."),
            (0, "Let's add a short cooldown to the skill, so it does not become too strong."),
            (1, "Agreed. After that, I will check the frame rate on an old phone."),
            (0, "Great. Let's playtest again on Friday."),
        ],
        "questions": [
            {"q": "What was the problem in the playtest?", "options": ["The game was too easy", "Most players lost in the first minute", "The game had no sound", "The camera was broken"], "answer": 1, "why": "Çoğu oyuncu ilk dakikada kaybetti."},
            {"q": "How will they fix the difficulty curve?", "options": ["Spawn fewer enemies at the beginning", "Remove all power-ups", "Make the game longer", "Change the music"], "answer": 0, "why": "Başta daha az düşman çıkaracaklar."},
            {"q": "Why will the programmer make the spike collider smaller?", "options": ["It feels unfair to players", "It uses too much memory", "The artist asked", "It is a bug in the engine"], "answer": 0, "why": "Oyuncular haksızlık gibi hissediyor."},
            {"q": "What will they check on an old phone?", "options": ["The frame rate", "The sound", "The price", "The screen color"], "answer": 0, "why": "Kare hızı (frame rate)."},
        ],
    },
    {
        "id": "ai-tools-at-work", "title": "Using AI Tools Wisely", "level": "B2", "minutes": 2,
        "about": "Bir mentor ve bir stajyer, yapay zeka araçlarını kod yazarken nasıl güvenle kullanacaklarını konuşuyor.",
        "lines": [
            (0, "I noticed you used an AI assistant to write the function. How did it go?"),
            (1, "It was fast, but the first answer had a hallucination. It used a method that does not exist."),
            (0, "That happens often. The important part is that you checked the result instead of trusting it."),
            (1, "I ran the tests, and they failed. Then I read the documentation and fixed the code myself."),
            (0, "Exactly. Treat the assistant like a fast but sometimes careless colleague."),
            (1, "Should I tell the team when I use it?"),
            (0, "Yes. Be open about it, and never paste private data or passwords into a prompt."),
            (1, "That makes sense. I also want to understand every line I submit, not just copy it."),
            (0, "That is the right attitude. If you cannot explain the code, you do not own it yet."),
            (1, "I will remember that. Thank you for the advice."),
        ],
        "questions": [
            {"q": "What was wrong with the first answer of the assistant?", "options": ["It was too slow", "It used a method that does not exist", "It had no code", "It was in another language"], "answer": 1, "why": "Var olmayan bir metot kullanmıştı (halüsinasyon)."},
            {"q": "How did the intern find the problem?", "options": ["By running the tests", "By asking a friend", "By guessing", "By restarting the computer"], "answer": 0, "why": "Testleri çalıştırınca başarısız oldular."},
            {"q": "What should you never paste into a prompt?", "options": ["Questions", "Private data or passwords", "Error messages without secrets", "Short examples"], "answer": 1, "why": "Özel veri ve parolalar."},
            {"q": "What does the mentor say about code you cannot explain?", "options": ["It is fine", "You do not own it yet", "Delete the repository", "Send it to the client"], "answer": 1, "why": "Açıklayamıyorsan henüz sana ait değil."},
        ],
    },
]

SENTENCES += [
    ("Hot reload lets me see my changes in the app instantly.", "B1", "Hot reload değişikliklerimi uygulamada anında görmemi sağlıyor."),
    ("The app needs permission to use the microphone.", "A2", "Uygulamanın mikrofonu kullanmak için izne ihtiyacı var."),
    ("I have to renew the certificate every seven days.", "B1", "Sertifikayı yedi günde bir yenilemek zorundayım."),
    ("The player's collider touches the wall and the character stops.", "B1", "Oyuncunun çarpışma alanı duvara değiyor ve karakter duruyor."),
    ("A smooth difficulty curve keeps the players interested.", "B2", "Yumuşak bir zorluk eğrisi oyuncuların ilgisini canlı tutar."),
    ("We spawn a new enemy every three seconds.", "A2", "Her üç saniyede bir yeni düşman oluşturuyoruz."),
    ("The model learned the training data too well and failed on new examples.", "B2", "Model eğitim verisini fazla iyi öğrendi ve yeni örneklerde başarısız oldu."),
    ("Always check the answer of an AI assistant before you use it.", "B1", "Bir yapay zeka asistanının cevabını kullanmadan önce mutlaka kontrol et."),
    ("Data cleaning is often the longest part of a project.", "B2", "Veri temizleme çoğu zaman bir projenin en uzun kısmıdır."),
    ("The game runs at sixty frames per second on my phone.", "A2", "Oyun telefonumda saniyede altmış kare hızla çalışıyor."),
]
